version: '3'

services:

  app:
    build:
      context: ./node
      dockerfile: Dockerfile.prod 
    image: ikesalmonson/node_app_proxy:prod
    container_name: app   
    entrypoint: sh -c "npm install -y && npm run  node_start " 
    networks: 
      - node-network
    volumes: 
      - ./node:/usr/src/app 

    tty: true  
    depends_on:
      db:
        condition: service_healthy

   

  nginx:
    image: nginx:1.24.0-alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - node-network 
    ports: 
      - 8080:80
    depends_on:
      - app  

  db:
    image: mysql:5.7
    container_name: db
    restart: always 
    tty: true
    volumes:
     - ./mysql_init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER = root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:     
      - node-network  


networks:
  node-network:
    driver: bridge  