
FROM node:18


WORKDIR /usr/src/app



COPY . .

ENV DOCKERIZE_VERSION v0.6.1

RUN apt-get update  &&  apt-get install -y wget

RUN wget -O - https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz | tar xzf - -C /usr/local/bin 
RUN apt-get autoremove -yqq --purge wget && rm -rf /var/lib/apt/lists/*

#EXPOSE 3000 

ENTRYPOINT [ "node", "index.js" ]